#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(dirname "$SCRIPT_DIR")/lib"

if [[ -f "$LIB_DIR/logger.sh" ]]; then
    source "$LIB_DIR/logger.sh"
else
    log_info() { echo -e "\033[0;34m[i]\033[0m $1"; }
    log_success() { echo -e "\033[0;32m[✓]\033[0m $1"; }
    log_error() { echo -e "\033[0;31m[✗]\033[0m $1" >&2; }
    log_warn() { echo -e "\033[0;33m[!]\033[0m $1"; }
    log_section() { echo -e "\n\033[0;36m═══════════════════════════════════════════════════════\033[0m"; echo -e "\033[0;36m  $1\033[0m"; echo -e "\033[0;36m═══════════════════════════════════════════════════════\033[0m\n"; }
fi

CONFIG_DIR="$HOME/.openclaw"
WORKSPACE_DIR="$HOME/.openclaw/workspace"
ENV_FILE="$WORKSPACE_DIR/.env"

show_welcome() {
    clear
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║   🚀 OpenClaw Post-Install Setup Wizard                   ║"
    echo "║                                                            ║"
    echo "║   This wizard will help you configure:                     ║"
    echo "║   • AI/LLM API keys (Claude, OpenAI, Gemini)              ║"
    echo "║   • CLI tool authentication                                ║"
    echo "║   • MCP server integrations                                ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
}

detect_installed_modules() {
    local -a modules=()
    
    command -v claude &>/dev/null && modules+=("claude")
    command -v openai &>/dev/null && modules+=("openai")
    [[ -f "$HOME/.local/venv/openclaw/bin/activate" ]] && {
        source "$HOME/.local/venv/openclaw/bin/activate" 2>/dev/null
        python3 -c "import google.generativeai" 2>/dev/null && modules+=("gemini")
        python3 -c "import anthropic" 2>/dev/null && [[ ! " ${modules[*]} " =~ " claude " ]] && modules+=("anthropic-sdk")
        python3 -c "import openai" 2>/dev/null && [[ ! " ${modules[*]} " =~ " openai " ]] && modules+=("openai-sdk")
        deactivate 2>/dev/null || true
    }
    
    [[ -f "$CONFIG_DIR/productivity/google-calendar-setup.md" ]] && modules+=("google-calendar")
    [[ -f "$CONFIG_DIR/productivity/google-drive-setup.md" ]] && modules+=("google-drive")
    [[ -f "$CONFIG_DIR/productivity/todoist-setup.md" ]] && modules+=("todoist")
    [[ -f "$CONFIG_DIR/productivity/slack-setup.md" ]] && modules+=("slack")
    [[ -f "$CONFIG_DIR/productivity/email-credentials.template.env" ]] && modules+=("email")
    
    echo "${modules[@]}"
}

ensure_env_file() {
    mkdir -p "$WORKSPACE_DIR"
    if [[ ! -f "$ENV_FILE" ]]; then
        cat > "$ENV_FILE" <<'ENVTEMPLATE'
# OpenClaw Environment Configuration
# Generated by openclaw-setup

# ─────────────────────────────────────────────────────────────────
# AI/LLM API Keys
# ─────────────────────────────────────────────────────────────────

# Anthropic (Claude) - https://console.anthropic.com/
ANTHROPIC_API_KEY=

# OpenAI (GPT) - https://platform.openai.com/api-keys
OPENAI_API_KEY=

# Google (Gemini) - https://aistudio.google.com/apikey
GOOGLE_API_KEY=

# ─────────────────────────────────────────────────────────────────
# MCP Server Tokens
# ─────────────────────────────────────────────────────────────────

# GitHub - https://github.com/settings/tokens
GITHUB_PAT=

# Todoist - https://todoist.com/prefs/integrations
TODOIST_API_TOKEN=

# Slack Bot Token - https://api.slack.com/apps
SLACK_BOT_TOKEN=

# Brave Search - https://brave.com/search/api/
BRAVE_API_KEY=

# ─────────────────────────────────────────────────────────────────
# Email Configuration (for email MCP server)
# ─────────────────────────────────────────────────────────────────

EMAIL_IMAP_HOST=imap.gmail.com
EMAIL_IMAP_PORT=993
EMAIL_SMTP_HOST=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_USERNAME=
EMAIL_PASSWORD=

# ─────────────────────────────────────────────────────────────────
# Database (auto-configured)
# ─────────────────────────────────────────────────────────────────

DATABASE_PATH=data/memory.db
MEMORY_DIR=memory
LOGS_DIR=memory/logs
ENVTEMPLATE
        chmod 0600 "$ENV_FILE"
        log_success "Created .env file: $ENV_FILE"
    fi
}

get_env_value() {
    local key="$1"
    local value=""
    if [[ -f "$ENV_FILE" ]]; then
        value=$(grep "^${key}=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'")
    fi
    echo "$value"
}

set_env_value() {
    local key="$1"
    local value="$2"
    
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        if [[ "$(uname)" == "Darwin" ]]; then
            sed -i '' "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
        else
            sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
        fi
    else
        echo "${key}=${value}" >> "$ENV_FILE"
    fi
}

configure_anthropic() {
    log_section "Anthropic (Claude) Configuration"
    
    local current_key=$(get_env_value "ANTHROPIC_API_KEY")
    
    if [[ -n "$current_key" && "$current_key" != "sk-ant-your-key-here" ]]; then
        log_success "Anthropic API key already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Get your API key from: https://console.anthropic.com/"
    echo ""
    read -r -p "Enter your Anthropic API key (or press Enter to skip): " api_key
    
    if [[ -n "$api_key" ]]; then
        if [[ "$api_key" =~ ^sk-ant- ]]; then
            set_env_value "ANTHROPIC_API_KEY" "$api_key"
            log_success "Anthropic API key saved"
            
            if command -v claude &>/dev/null; then
                echo ""
                read -r -p "Authenticate Claude CLI now? [Y/n] " response
                if [[ ! "$response" =~ ^[Nn]$ ]]; then
                    log_info "Running: claude login"
                    claude login || log_warn "Claude login may have failed"
                fi
            fi
        else
            log_warn "Key doesn't look like an Anthropic key (expected sk-ant-...)"
            read -r -p "Save anyway? [y/N] " response
            [[ "$response" =~ ^[Yy]$ ]] && set_env_value "ANTHROPIC_API_KEY" "$api_key"
        fi
    else
        log_info "Skipped Anthropic configuration"
    fi
}

configure_openai() {
    log_section "OpenAI Configuration"
    
    local current_key=$(get_env_value "OPENAI_API_KEY")
    
    if [[ -n "$current_key" && "$current_key" != "sk-proj-your-key-here" ]]; then
        log_success "OpenAI API key already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Get your API key from: https://platform.openai.com/api-keys"
    echo ""
    read -r -p "Enter your OpenAI API key (or press Enter to skip): " api_key
    
    if [[ -n "$api_key" ]]; then
        if [[ "$api_key" =~ ^sk- ]]; then
            set_env_value "OPENAI_API_KEY" "$api_key"
            log_success "OpenAI API key saved"
        else
            log_warn "Key doesn't look like an OpenAI key (expected sk-...)"
            read -r -p "Save anyway? [y/N] " response
            [[ "$response" =~ ^[Yy]$ ]] && set_env_value "OPENAI_API_KEY" "$api_key"
        fi
    else
        log_info "Skipped OpenAI configuration"
    fi
}

configure_gemini() {
    log_section "Google Gemini Configuration"
    
    local current_key=$(get_env_value "GOOGLE_API_KEY")
    
    if [[ -n "$current_key" && "$current_key" != "your-google-api-key-here" ]]; then
        log_success "Google API key already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Get your API key from: https://aistudio.google.com/apikey"
    echo ""
    read -r -p "Enter your Google API key (or press Enter to skip): " api_key
    
    if [[ -n "$api_key" ]]; then
        set_env_value "GOOGLE_API_KEY" "$api_key"
        log_success "Google API key saved"
    else
        log_info "Skipped Gemini configuration"
    fi
}

configure_github() {
    log_section "GitHub Configuration"
    
    local current_key=$(get_env_value "GITHUB_PAT")
    
    if [[ -n "$current_key" ]]; then
        log_success "GitHub PAT already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Create a Personal Access Token at: https://github.com/settings/tokens"
    echo "Required scopes: repo, read:org (for MCP server)"
    echo ""
    read -r -p "Enter your GitHub PAT (or press Enter to skip): " token
    
    if [[ -n "$token" ]]; then
        if [[ "$token" =~ ^gh[ps]_ ]]; then
            set_env_value "GITHUB_PAT" "$token"
            log_success "GitHub PAT saved"
        else
            log_warn "Token format looks unusual (expected ghp_... or ghs_...)"
            read -r -p "Save anyway? [y/N] " response
            [[ "$response" =~ ^[Yy]$ ]] && set_env_value "GITHUB_PAT" "$token"
        fi
    else
        log_info "Skipped GitHub configuration"
    fi
}

configure_todoist() {
    log_section "Todoist Configuration"
    
    local current_key=$(get_env_value "TODOIST_API_TOKEN")
    
    if [[ -n "$current_key" ]]; then
        log_success "Todoist API token already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Get your API token from: https://todoist.com/prefs/integrations"
    echo "(Scroll down to 'API token')"
    echo ""
    read -r -p "Enter your Todoist API token (or press Enter to skip): " token
    
    if [[ -n "$token" ]]; then
        set_env_value "TODOIST_API_TOKEN" "$token"
        log_success "Todoist API token saved"
    else
        log_info "Skipped Todoist configuration"
    fi
}

configure_slack() {
    log_section "Slack Configuration"
    
    local current_key=$(get_env_value "SLACK_BOT_TOKEN")
    
    if [[ -n "$current_key" ]]; then
        log_success "Slack Bot token already configured"
        read -r -p "Update it? [y/N] " response
        [[ ! "$response" =~ ^[Yy]$ ]] && return 0
    fi
    
    echo ""
    echo "Setup instructions: ~/.openclaw/productivity/slack-setup.md"
    echo "Or visit: https://api.slack.com/apps"
    echo ""
    read -r -p "Enter your Slack Bot Token (xoxb-...) or press Enter to skip: " token
    
    if [[ -n "$token" ]]; then
        if [[ "$token" =~ ^xoxb- ]]; then
            set_env_value "SLACK_BOT_TOKEN" "$token"
            log_success "Slack Bot token saved"
        else
            log_warn "Token format looks unusual (expected xoxb-...)"
            read -r -p "Save anyway? [y/N] " response
            [[ "$response" =~ ^[Yy]$ ]] && set_env_value "SLACK_BOT_TOKEN" "$token"
        fi
    else
        log_info "Skipped Slack configuration"
    fi
}

configure_google_services() {
    log_section "Google Services (Calendar/Drive)"
    
    local creds_file="$CONFIG_DIR/google-credentials.json"
    
    if [[ -f "$creds_file" ]]; then
        log_success "Google OAuth credentials already configured"
        return 0
    fi
    
    echo ""
    echo "Google Calendar and Drive require OAuth credentials."
    echo ""
    echo "Quick setup:"
    echo "  1. Go to: https://console.cloud.google.com/"
    echo "  2. Create a project (or select existing)"
    echo "  3. Enable 'Google Calendar API' and 'Google Drive API'"
    echo "  4. Create OAuth 2.0 credentials (Desktop app)"
    echo "  5. Download the JSON file"
    echo ""
    
    read -r -p "Do you have a credentials JSON file ready? [y/N] " response
    
    if [[ "$response" =~ ^[Yy]$ ]]; then
        read -r -p "Enter path to credentials JSON: " creds_path
        
        if [[ -f "$creds_path" ]]; then
            mkdir -p "$CONFIG_DIR"
            cp "$creds_path" "$creds_file"
            chmod 0600 "$creds_file"
            
            cp "$creds_path" "$CONFIG_DIR/google-calendar-credentials.json"
            cp "$creds_path" "$CONFIG_DIR/google-drive-credentials.json"
            chmod 0600 "$CONFIG_DIR/google-calendar-credentials.json"
            chmod 0600 "$CONFIG_DIR/google-drive-credentials.json"
            
            log_success "Google credentials saved"
            echo ""
            log_info "To complete authentication, run:"
            echo "  openclaw-auth --google-calendar"
            echo "  openclaw-auth --google-drive"
        else
            log_error "File not found: $creds_path"
        fi
    else
        log_info "Skipped Google services configuration"
        echo ""
        echo "See detailed setup guide:"
        echo "  cat ~/.openclaw/productivity/google-calendar-setup.md"
    fi
}

show_summary() {
    log_section "Configuration Summary"
    
    echo "Checking configured services..."
    echo ""
    
    local anthropic_key=$(get_env_value "ANTHROPIC_API_KEY")
    local openai_key=$(get_env_value "OPENAI_API_KEY")
    local google_key=$(get_env_value "GOOGLE_API_KEY")
    local github_pat=$(get_env_value "GITHUB_PAT")
    local todoist_token=$(get_env_value "TODOIST_API_TOKEN")
    local slack_token=$(get_env_value "SLACK_BOT_TOKEN")
    
    [[ -n "$anthropic_key" && "$anthropic_key" != *"your-key"* ]] && echo "  ✓ Anthropic (Claude)" || echo "  ○ Anthropic (not configured)"
    [[ -n "$openai_key" && "$openai_key" != *"your-key"* ]] && echo "  ✓ OpenAI" || echo "  ○ OpenAI (not configured)"
    [[ -n "$google_key" && "$google_key" != *"your-key"* ]] && echo "  ✓ Google Gemini" || echo "  ○ Google Gemini (not configured)"
    [[ -n "$github_pat" ]] && echo "  ✓ GitHub" || echo "  ○ GitHub (not configured)"
    [[ -n "$todoist_token" ]] && echo "  ✓ Todoist" || echo "  ○ Todoist (not configured)"
    [[ -n "$slack_token" ]] && echo "  ✓ Slack" || echo "  ○ Slack (not configured)"
    [[ -f "$CONFIG_DIR/google-credentials.json" ]] && echo "  ✓ Google Calendar/Drive" || echo "  ○ Google Calendar/Drive (not configured)"
    
    echo ""
    echo "Configuration file: $ENV_FILE"
    echo ""
    echo "Next steps:"
    echo "  • Reload shell: source ~/.bashrc"
    echo "  • Validate setup: openclaw-validate"
    echo "  • View all configs: cat $ENV_FILE"
    echo ""
}

run_interactive_setup() {
    show_welcome
    ensure_env_file
    
    echo "Which services would you like to configure?"
    echo ""
    echo "  1) All services (recommended for new users)"
    echo "  2) AI/LLM APIs only (Claude, OpenAI, Gemini)"
    echo "  3) Productivity integrations only (GitHub, Todoist, Slack)"
    echo "  4) Google services only (Calendar, Drive)"
    echo "  5) Individual service selection"
    echo "  6) Run OpenClaw onboard wizard (recommended for first-time setup)"
    echo "  q) Quit"
    echo ""
    read -r -p "Select option [1]: " choice
    choice="${choice:-1}"

    case "$choice" in
        1)
            configure_anthropic
            configure_openai
            configure_gemini
            configure_github
            configure_todoist
            configure_slack
            configure_google_services
            ;;
        2)
            configure_anthropic
            configure_openai
            configure_gemini
            ;;
        3)
            configure_github
            configure_todoist
            configure_slack
            ;;
        4)
            configure_google_services
            ;;
        5)
            echo ""
            echo "Select services to configure (space-separated numbers):"
            echo "  1) Anthropic (Claude)"
            echo "  2) OpenAI"
            echo "  3) Google Gemini"
            echo "  4) GitHub"
            echo "  5) Todoist"
            echo "  6) Slack"
            echo "  7) Google Calendar/Drive"
            echo ""
            read -r -p "Services: " services
            
            for svc in $services; do
                case "$svc" in
                    1) configure_anthropic ;;
                    2) configure_openai ;;
                    3) configure_gemini ;;
                    4) configure_github ;;
                    5) configure_todoist ;;
                    6) configure_slack ;;
                    7) configure_google_services ;;
                esac
            done
            ;;
        6)
            log_section "OpenClaw Onboard Wizard"
            if command -v openclaw &>/dev/null; then
                log_info "Running: openclaw onboard --install-daemon"
                openclaw onboard --install-daemon || log_warn "Onboard wizard had issues"
            else
                log_error "openclaw command not found. Install it first (module 13-openclaw.sh)"
            fi
            ;;
        q|Q)
            log_info "Setup cancelled"
            exit 0
            ;;
        *)
            log_error "Invalid option"
            exit 1
            ;;
    esac

    show_summary
}

usage() {
    cat <<EOF
OpenClaw Post-Install Setup Wizard

Usage: $0 [OPTIONS]

OPTIONS:
    -h, --help          Show this help message
    --all               Configure all services (non-interactive)
    --llm               Configure AI/LLM APIs only
    --productivity      Configure productivity integrations only
    --google            Configure Google services only
    --anthropic         Configure Anthropic only
    --openai            Configure OpenAI only
    --gemini            Configure Gemini only
    --github            Configure GitHub only
    --todoist           Configure Todoist only
    --slack             Configure Slack only

Without options, runs in interactive mode.

EXAMPLES:
    $0                  # Interactive wizard
    $0 --llm            # Configure Claude, OpenAI, Gemini
    $0 --anthropic      # Configure only Anthropic

EOF
}

main() {
    ensure_env_file
    
    if [[ $# -eq 0 ]]; then
        run_interactive_setup
        exit 0
    fi
    
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                usage
                exit 0
                ;;
            --all)
                configure_anthropic
                configure_openai
                configure_gemini
                configure_github
                configure_todoist
                configure_slack
                configure_google_services
                shift
                ;;
            --llm)
                configure_anthropic
                configure_openai
                configure_gemini
                shift
                ;;
            --productivity)
                configure_github
                configure_todoist
                configure_slack
                shift
                ;;
            --google)
                configure_google_services
                shift
                ;;
            --anthropic)
                configure_anthropic
                shift
                ;;
            --openai)
                configure_openai
                shift
                ;;
            --gemini)
                configure_gemini
                shift
                ;;
            --github)
                configure_github
                shift
                ;;
            --todoist)
                configure_todoist
                shift
                ;;
            --slack)
                configure_slack
                shift
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done
    
    show_summary
}

main "$@"
